ignore:
  - "external"
  - "simulator/export/cen64/*.h"
  - "simulator/export/cen64/*.cpp"
  - "simulator/export/gdb/*.h"
  - "simulator/export/gdb/*.cpp"

codecov:
  require_ci_to_pass: yes
  max_report_age: off
