# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Visualizer CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      working-directory: visualizer
      run: npm install
    - name: Testing
      working-directory: visualizer
      run: npm test
    - name: Testing with coverage 
      working-directory: visualizer
      run: npx nyc --reporter=lcov npm test
    - name: Codecov
      working-directory: visualizer
      run: npx codecov
